# Generated by Django 4.2.11 on 2024-10-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property_Dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingexpenses',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='property_id',
        ),
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='Property_Dashboard_app.property'),
            preserve_default=False,
        ),
    ]
